#!/usr/bin/env ruby
$:.unshift File.join(File.dirname(__FILE__), "../lib")
require 'proxifier'

if ARGV[0] == "--second"
  puts "Gettin proxy from #{ARGV[1]}"
  runner = Proxifier::Runner.new(ARGV[1])
  runner.call
  exit
end

system "sudo proxifier --second #{ARGV[0]}"
